#!/usr/bin/env python3
"""
ROBOT 2: MUSIC GENERATOR
========================

Reads project.json from Robot 1 and generates music using AudioCraft MusicGen.

Usage:
    python run.py --config ../config/project.json
    python run.py --config ../config/project.json --model medium --output ../output/music.wav
"""

import json
import argparse
import sys
from pathlib import Path
from typing import Any

import soundfile as sf

from musicgen_engine import MusicGenEngine


def load_project_config(path: Path) -> dict[str, Any]:
    """
    Load and parse the project configuration JSON file.
    
    Args:
        path: Path to the project.json file
    
    Returns:
        Parsed configuration dictionary
    
    Raises:
        FileNotFoundError: If config file doesn't exist
        json.JSONDecodeError: If config file is invalid JSON
    """
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def validate_music_config(config: dict[str, Any]) -> dict[str, Any]:
    """
    Validate and extract music configuration with defaults.
    
    Args:
        config: Full project configuration
    
    Returns:
        Music configuration dictionary with validated values
    
    Raises:
        KeyError: If required 'music' section is missing
    """
    if "music" not in config:
        raise KeyError("Configuration missing required 'music' section")
    
    music_cfg = config["music"]
    
    # Apply defaults for optional fields
    return {
        "prompt": music_cfg.get("prompt", "ambient electronic music"),
        "bpm": int(music_cfg.get("bpm", 120)),
        "duration_seconds": int(music_cfg.get("duration_seconds", 30)),
        "style": music_cfg.get("style", "electronic"),
        "key": music_cfg.get("key", "Am"),
    }


def main() -> int:
    """
    Main entry point for the music generator.
    
    Returns:
        Exit code (0 for success, 1 for error)
    """
    parser = argparse.ArgumentParser(
        description="Robot 2: Music Generator - Generate music with MusicGen",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python run.py --config ../config/project.json
  python run.py --config ../config/project.json --model medium
  python run.py --config ../config/project.json --output ./my_music.wav
        """
    )

    parser.add_argument(
        "--config",
        type=str,
        default="../config/project.json",
        help="Path to project.json generated by Robot 1",
    )

    parser.add_argument(
        "--model",
        type=str,
        default="small",
        choices=["small", "medium", "large", "melody"],
        help="MusicGen model size (default: small)",
    )

    parser.add_argument(
        "--output",
        type=str,
        default="../output/music.wav",
        help="Output path for generated audio file",
    )

    args = parser.parse_args()

    config_path = Path(args.config)
    output_path = Path(args.output)
    
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("ROBOT 2: MUSIC GENERATOR")
    print("=" * 60)
    print(f"Config: {config_path}")
    print(f"Model:  {args.model}")
    print(f"Output: {output_path}")
    print("=" * 60)
    print()

    try:
        # Load configuration
        print("→ Loading project config...")
        config = load_project_config(config_path)
        music_cfg = validate_music_config(config)
        
        print(f"  Style: {music_cfg['style']}")
        print(f"  BPM: {music_cfg['bpm']}")
        print(f"  Duration: {music_cfg['duration_seconds']}s")
        print(f"  Key: {music_cfg['key']}")
        print()

        # Initialize engine
        engine = MusicGenEngine(model_size=args.model)
        print()

        # Generate audio
        audio = engine.generate(
            prompt=music_cfg["prompt"],
            duration_seconds=music_cfg["duration_seconds"],
            bpm=music_cfg["bpm"],
        )

        # Save WAV file
        print(f"\n→ Saving audio to {output_path}...")
        
        # Transpose from (channels, samples) to (samples, channels) for soundfile
        sf.write(
            str(output_path), 
            audio.T, 
            samplerate=engine.get_sample_rate()
        )

        print()
        print("=" * 60)
        print("✓ MUSIC SUCCESSFULLY GENERATED")
        print("=" * 60)
        print(f"Saved to: {output_path}")
        print(f"Duration: {music_cfg['duration_seconds']}s")
        print(f"Sample rate: {engine.get_sample_rate()} Hz")
        print("=" * 60)
        
        return 0

    except FileNotFoundError as e:
        print(f"\n✗ ERROR: {e}")
        print("\nMake sure Robot 1 has generated the config file first:")
        print("  cd robot_script && python run.py --output ../config/project.json")
        return 1
    
    except KeyError as e:
        print(f"\n✗ ERROR: Invalid configuration - {e}")
        return 1
    
    except Exception as e:
        print(f"\n✗ ERROR: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
