"""
ROBOT 2: MUSIC GENERATOR
========================
Reads project.json from Robot 1
→ Generates music using AudioCraft MusicGen
→ Saves to ../output/music.wav
"""

import json
import argparse
from pathlib import Path

import soundfile as sf

from musicgen_engine import MusicGenEngine


def load_project_config(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def main():
    parser = argparse.ArgumentParser(description="Robot 2: Music Generator")

    parser.add_argument(
        "--config",
        type=str,
        default="../config/project.json",
        help="Path to project.json generated by Robot 1.",
    )

    parser.add_argument(
        "--model",
        type=str,
        default="small",
        help="MusicGen model: small, medium, large, melody",
    )

    parser.add_argument(
        "--output",
        type=str,
        default="../output/music.wav",
        help="Where to save the generated audio file.",
    )

    args = parser.parse_args()

    config_path = Path(args.config)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print("============================================================")
    print("ROBOT 2: MUSIC GENERATOR")
    print("============================================================")
    print(f"Config: {config_path}")
    print(f"Model: {args.model}")
    print(f"Output: {output_path}")
    print("============================================================\n")

    # Load JSON
    print("→ Loading project config...")
    config = load_project_config(config_path)

    music_cfg = config["music"]
    prompt = music_cfg["prompt"]
    bpm = int(music_cfg["bpm"])
    duration = int(music_cfg["duration_seconds"])

    # Load MusicGen
    engine = MusicGenEngine(model_size=args.model)

    # Generate audio
    audio = engine.generate(
        prompt=prompt,
        duration_seconds=duration,
        bpm=bpm,
    )

    # Save WAV
    print(f"\n→ Saving audio to {output_path} ...")
    sf.write(output_path, audio.T, samplerate=32000)

    print("\n============================================================")
    print("✓ MUSIC SUCCESSFULLY GENERATED")
    print("============================================================")
    print(f"Saved to: {output_path}")


if __name__ == "__main__":
    main()